### ISSUE TITLE
Ignore cloudflare referers

### ISSUE THREAD

**Issue by Absolucy** [kooparse/bast#108]
There's many referers from Cloudflare challenges, such as these:

![image](https://user-images.githubusercontent.com/65794972/103464657-7c43f080-4d03-11eb-809c-2807c57826ca.png)

Would be nice if query strings could be ignored in the referer statsitics

**Comment by kooparse** [comment]
Hi! I like the idea! Also, it's easy to add it to the project so I will see to add it soon ;)
