### ISSUE TITLE
Why load the script in the head ?

### ISSUE THREAD

**Issue by fabienheureux** [kooparse/bast#5]
Couldn't we split the external script loading and the tag that executes on the page ? 
This could be problematic to load script in the head as it can slows the rest of the webpage's loading.

Loading the script tag as the last thing in the `<body>` could prevent this issue.

**Comment by kooparse** [comment]
Indeed, the external script isn't async right now. 
So I just made some changes about it: 

1) The external script will be loaded asynchronously if the client browser support it.
2) If not we fall back on `defer`, so the external script will be loaded only after the whole page is parsed.
3) I changed the message in settings, to explains a bit more about those things, and why/how you should place your script depending on (maybe) your audience target (old browsers? etc...). 

Cool links explaining this subject:
https://stackoverflow.com/questions/436411/where-should-i-put-script-tags-in-html-markup/24070373#24070373
https://html.spec.whatwg.org/multipage/scripting.html#attr-script-defer
