### ISSUE TITLE
Have a week view

### ISSUE THREAD

**Issue by fabienheureux** [kooparse/bast#9]
A good addition to the dashboard would be to have a per week / per day view. 

Currently, this is quite frustrating to have close to no audience on first months of use :) 
![image](https://user-images.githubusercontent.com/1702255/80413786-4925a380-88d0-11ea-9e14-0a97530e2e22.png) 

Like Cloudflare does maybe..
![image](https://user-images.githubusercontent.com/1702255/80413891-740ff780-88d0-11ea-847f-0b0451d06156.png)

**Comment by kooparse** [comment]
Clearly something that I would like to add to the project. We already have everything needed as our analytic granularity is days currently. We just have to think about the UI on the front, and the proper function to process weeks/days on the back! 

I don't know yet when I'll be able to do that!

**Comment by kooparse** [comment]
In fact, it's done! 💯 
(see https://github.com/kooparse/bast/commit/81c16f8e9663f9266530a3a9fedd4d892be6ace1)
